### PR TITLE
Make "Objective-C compatibility" header bigger

### PR DESCRIPTION
**Pull request by mattab**

### CODE REVIEW

**Comment by brototyp** [comment]
What do you think about instead of making the header bigger to link this header from right from the top? Something like "written in Swift, [compatible with Objective-C](link to the header)"?

**Comment by brototyp** [comment]
@mattab I just did that. Let me know if you are fine with this change.

**Comment by mattab** [comment]
:+1: 

 Maybe also rename "Advanced" to "Advanced usage" and make titles below the right level so they are bigger and there are title less level.

**Comment by brototyp** [comment]
Good point.

**Pull request merged**
