### PR TITLE
Removed the url as required parameter

### PR DESCRIPTION
**Pull request by brototyp**
Fixes/Implements #194

What changed:

- The url parameter of an `Event` is now an optional parameter
- The convenience methods for view and event tracking have a new optional url parameter
- When not defining a url, no default url will be generated

Do we want to add a way to generate a default url? If so, this would be my proposal:

- Add a new property `contentBaseUrl` to the PiwikTracker
- If this property is set, every event that has no url set will generate one by its own
- To generate a url, it will use the `contentBaseUrl` and append the action-array as path

Example:
- `contentBaseUrl` is https://piwik.org
- actions is ["docs", "requirements"]
- the url will be https://piwik.org/docs/requirements

### CODE REVIEW

**Comment by thbaja** [comment]
I think this is a good PR.

And a very good proposal regarding the contentBaseUrl. Perhaps this should also apply for when tracking screens?

**Comment by brototyp** [comment]
Yes, I would apply the logic to all events that are tracked. It is a bit complicated to differentiate between an event and an `Event` where the latter includes events, screen views and all other kind of data send to the backend.

**Comment by thbaja** [comment]
Understood 👍

**Comment by brototyp** [comment]
Just released [version 4.4.0](https://github.com/piwik/piwik-sdk-ios/releases/tag/v4.4.0) containing this change.

**Pull request merged**
