### PR TITLE
Privacy Manifest

### PR DESCRIPTION
**Pull request by felipe-nipper**
- Added Privacy Manifest file as required by [Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

### CODE REVIEW

**Comment by brototyp** [comment]
Thanks for the contribution! LGTM. I'll let the tests pass and merge

**Comment by brototyp** [comment]
Merged and part of Version 7.6.0

**Comment by pau-lu** [comment]
Hi @felipe-nipper -  a quick question - does the manifest only disclose NSPrivacyAccessedAPITypes because NS PrivacyTracking, NSPrivacyTrackingDomains and NSPrivacyCollectedDataTypes are not applicable? The 2nd note here https://developer.apple.com/documentation/bundleresources/privacy_manifest_filesnote also says "You only need to supply NSPrivacyAccessedAPITypes for apps and 3rd party SDKs on iOS" but I think this means that NSPrivacyAccessedAPITypes dictionary is required in those SDKs in addition to the 3 above (to the extent they are applicable). Thank you.

**Comment by felipe-nipper** [comment]
Hi @pau-lu, the values of NSPrivacyTracking, NSPrivacyTrackingDomains, and NSPrivacyCollectedDataTypes can change based on how you use the data. For instance, your usage of Matomo doesn't necessarily fit into the tracking requirements set by Apple. Hence, the values you're required to delineate can vary by project. Keeping this in mind, you should input this information at your app level and not in the third-party SDK. Additionally, it seems that NSPrivacyTrackingDomains and NSPrivacyCollectedDataTypes are not necessarily required.

**Comment by pau-lu** [comment]
Hi @felipe-nipper - thank you!

**Pull request merged**
