### PR TITLE
Fixed macOS version recognition

### LINKED ISSUE #361: Device Detection for Mac broken since 7.3
I recently updated the Matomo SDK in my app to the latest version (7.3). Looking at the `operation system statistics`, more and more generic `Mac` systems w/o a detected version number popped up. I'm realizing now that it's completely broken since this change https://github.com/matomo-org/matomo-sdk-ios/pull/353.

A generated User-Agent from my Mac app looks like this:

`AppName/1.0 x86_64 macOS/11.0.1 MatomoTrackerSDK/7.3 Darwin/20.1.0`

And trying it out with the [device detector demo](https://devicedetector.lw1.at/AppName%2F1.0%20x86_64%20macOS%2F11.0.1%20MatomoTrackerSDK%2F7.3%20Darwin%2F20.1.0) confirms, that it's broken.

The old `User-Agent` generated from an earlier SDK version obviously works (But detects the OS wrong, it's 11.0 or 10.16 and not 10.15.6):

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) MatomoTracker SDK URLSessionDispatcher`

The question is: Should this be fixed in the client iOS/Mac SDK or on the server side? Help? 😊

### PR DESCRIPTION
**Pull request by brototyp**
Fixes #361

### CODE REVIEW

**Comment by lrrrs** [comment]
👍 Thanks. A generated `User-Agent` now looks like this `Darwin/20.1.0 (x86_64; Mac OS X 11.0.1) MatomoTrackerSDK/7.3 AppName/1.0` and the [Device Detector is able to parse it](https://devicedetector.lw1.at/Darwin%2F20.1.0%20(x86_64;%20Mac%20OS%20X%2011.0.1)%20MatomoTrackerSDK%2F7.3%20Tyme%203%2F2020.26).

🐑 it!

**Comment by Findus23** [comment]
@lrrrs I noticed that your link wasn't working and it seems like there was a bug in the website with the url parameters (and a typo). I also updated the UI so that it also visualizes the data if there is only OS data.

**Comment by lrrrs** [comment]
So, how can we get this merged? 🤷‍♂️

**Comment by brototyp** [comment]
Hi @lrrrs, thanks for pinging me here again. Non-OSS live was a bit full the last week so I completely forgot about this. I'll merge it now and will release a new version today. Thanks for your help!

**Comment by brototyp** [comment]
I actually want to wait for #363 before I release the next version.

**Pull request merged**
