### PR TITLE
Added a way of setting customTrackingParameters to an Event and tracking custom Events.

### PR DESCRIPTION
**Pull request by brototyp**
This is an implementation of #153, as an alternative of #154 which is much easier.

Example usage:
```swift
    private func example() {
        guard let piwikTracker = PiwikTracker.shared else { return }
        let downloadURL = URL(string: "https://builds.piwik.org/piwik.zip")!
        let event = Event(tracker: piwikTracker, action: ["menu", "some page", "downloadfile"], customTrackingParameters: ["download":downloadURL.absoluteString])
        PiwikTracker.shared?.track(event)
    }
```

Upsides: 
- Much easier usage. Create the event directly and the track it. No need to create intermediary events.
- Adds only two new functions. A new initializer for the Event and a new function to track an event directly.

### CODE REVIEW

**Comment by brototyp** [comment]
@minitrue22 Do you have any input to this?

**Comment by thorstenstark** [comment]
I like this way of setting custom parameters. But I'm currently not sure if this may have effects on the compatibility with obj-c.

**Comment by brototyp** [comment]
What currently works with objc will still work. We didn't change the interface. I'm not sure if we will be able to pull of objc compatibility for the new features.

**Comment by brototyp** [comment]
@thorstenstark I just implemented the rest, added example code and wrote the documentation.

**Pull request merged**
