### PR TITLE
Feature/fix swift header warnings and use correct access levels

### PR DESCRIPTION
**Pull request by mattmoncur**
- fix swift header warnings in **PiwikTracker.swift**
- use correct access levels in **Application.swift** and **Device.swift** extensions

### CODE REVIEW

**Comment by brototyp** [comment]
Hi @mattmoncur, thanks for you effort. Unfortunately I cannot see the warnings in the `PiwikTracker.swift`. When are they occurring?

**Comment by mattmoncur** [comment]
I was including PiwikTracker's source file directly in my project, and my auto generated **Project-Swift.h** header had the warnings. Xcode 9.2.

**Comment by brototyp** [comment]
Hi @mattmoncur, I see. I think your project uses Swift 3.2 or such. This project is using Swift version 4.0
Is it possible, that's the reason for your issues?

**Comment by brototyp** [comment]
I will close this for now. Please get back in touch with me if you think I am wrong.

**Comment by mattmoncur** [comment]
Sorry yes that was it, it also looks like your correct the siteID siteId mismatch in MatomoTracker.swift. Cheers
-Matt

**Comment by brototyp** [comment]
Thanks for your feedback and thanks for the effort of creating a PR.

**Pull request closed without merging**
