### PR TITLE
WIP: Added a way of setting customTrackingParameters to an Event and tracking custom Events.

### PR DESCRIPTION
**Pull request by brototyp**
Implements: #153 

* Added a `event()` function to the PiwikTracker that returns an empty event that has core properties already set, such as siteId, visitor, session and such.
* Added a `let customTrackingParameters: [String:String]` property to the Event
* Added a convenience initializer to the Event that copies over all properties from another event and overrides some.
* Added a function to the `PiwikTracker` that tracks a custom `Event`

See all those things in action over [here](https://github.com/piwik/piwik-sdk-ios/pull/154/files#diff-7eb09fef8dbfc0c57ff665277ab105c4R19).

Todo:

- [ ] Discuss if this is a good solution
- [ ] Add Documentation to the new public functions
- [ ] Add an entry in the Changelog
- [ ] Add documentation to the Readme

### CODE REVIEW

**Comment by luohui8891** [comment]
Hmm, great, I got it.
We setup `Piwik` in our platform and I should integrate this iOS SDK in our iOS APP.
I found that we just could use only the shared instance with version 3.3 (Objective-C version).
Then I reviewed and upgraded it to version 4.4 (Swift 3), I could create multi-Tracker for different sites (our business needed). But 4.4 didn't support custom variables.

Anyway, I got this branch. Great job.

**Comment by thorstenstark** [comment]
Adding custom parameters sounds like a good idea. But what happens when the custom parameters interfere with some (new) piwik parameters? Should piwik-owned parameters be protected in some kind from being overwritten?

**Comment by brototyp** [comment]
@thorstenstark That's an interesting question. I think it is fine, that the user is able to override existing properties. But we should say so in the documentation.

**Comment by brototyp** [comment]
An alternative implementation got merged.

**Pull request closed without merging**
