### PR TITLE
Support for Swift 5.0 and Xcode 10.2

### PR DESCRIPTION
**Pull request by joaomvfsantos**
What I did:

- Update code to Swift 5.0, this had the implication of also updating Quick to 2.0 and Nimble to 8.0 (both which now also support Swift 5.0)
- Update Xcode project settings

### CODE REVIEW

**Comment by brototyp** [comment]
Hey @joaomvfsantos, thanks a lot for your PR and sorry I didn't respond yet. I'll try to check out what's going on with the build error there and get back here.

**Comment by joaomvfsantos** [comment]
Hey @brototyp no problem. Thanks for looking into that, I'm not familiar with Travis CI so I appreciate that.

**Comment by brototyp** [comment]
Hey @joaomvfsantos, I fixed the issue with the CI in #294 and merged to develop. If you rebase from develop it should build just right.

**Review by brototyp — APPROVED** [review]

**Comment by joaomvfsantos** [comment]
@brototyp There seems to be something wrong still. `--no-document` is duplicated on the install step and CI is complaining about an invalid option `--no-ri`.

**Comment by brototyp** [comment]
Hey @joaomvfsantos, thanks for checking that out. I did a little more research (not the ruby pro here 😉) and I guess the following would help:

1. Change in `.travis.yml`
```yml
before_install:
  - 'echo ''gem: --no-ri --no-document'' > ~/.gemrc'
```

to
```yml
before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'
```

2. Change in `.travis.yml`
```yml
install:
  - gem install cocoapods --no-document --no-ri --no-document --quiet
  - gem install xcpretty --no-document --no-ri --no-document --quiet
```

to
```yml
install:
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
```

Can you try that out?

**Comment by joaomvfsantos** [comment]
Hey @brototyp, this did the trick, but now failing the tests for some reason on iOS 9. This also happens locally, I think that there must be some issue with Xcode 10.2, because it's not the tests themselves that are failing, but rather it fails right at the beginning. Could not figure this one out yet. Will try to give it a closer look.

**Comment by brototyp** [comment]
Hey @joaomvfsantos, thanks a lot for your effort on this PR here and that I wasn't to much of help there. Swift 5 Support was merged in #306 in the meantime. I'll close this PR for now.

**Pull request closed without merging**
